image: python:latest

stages:
  - format
  - test
  - deploy
  - install
  - release

format:
  stage: format
  script:
    - pip install black
    - black --check .
  except:
    - tags

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests
  except:
      - tags

pages:
  stage: deploy
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y && apt-get install pandoc -y
    - python -m pip install sphinx furo pydata_sphinx_theme
    - pip install -r requirements.txt
  script:
    - cd docs && make html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
      - public
  except:
      - tags
      
install:
  stage: install
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - python -c "import xevent"
  except:
    - tags

release:
  stage: release
  image: python:latest
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository pypi --skip-existing --verbose dist/* -u __token__ -p ${PYPI_API_TOKEN}
  only:
    - tags
