image: python:latest

stages:
  - format
  - test
  - deploy
  - install

format:
  stage: format
  script:
    - pip install black
    - black --check .

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

pages:
  stage: deploy
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx furo pydata_sphinx_theme
    - pip install -r requirements.txt
  script:
    - cd docs && make html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
    - public

 install:
  stage: install
  image: python:latest
  script:
    - pip install .
    - python -c "import xevent"
    